name: build-and-push.yml

on:
  push:
    branches:
      - main  # Triggers only when you push to the main branch
  workflow_dispatch: # Allows you to click a "Run workflow" button in

#  Required permissions for OIDC (OpenID Connect) authentication
permissions:
  id-token: write   # Required for requesting the JWT from AWS
  contents: read    # Required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # Prepend the common Docker locations to the PATH for the entire job
      PATH: /usr/local/bin:/usr/bin:/bin:/snap/bin:$PATH

    steps:
#       Step 1: Download the source code from your repo
      - name: Checkout Code
        uses: actions/checkout@v4

#       Fix: Install AWS CLI and Docker CLI in the runner container
      - name: Install required tools
        run: |
          apt-get update
          apt-get install -y awscli docker.io          

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

#       Step 2: Authenticate with AWS using OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}


#      Step 3: Authenticate Docker with your ECR registry manually
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr


#     Step 4: Build and push the image using a dedicated, optimized action
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Build context is the root of your repository
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/github-ecr-repo:${{ gitea.run_number }}            
